# ===================================
#  Form Behavior Config
# ===================================

name: Vidarebefordringar
form: @/plugins/engagementagency/redirectionist/models/redirection/fields.yaml
model-class: EngagementAgency\Redirectionist\Models\Redirection
default-redirect: engagementagency/redirectionist/redirections

create:
    title: Skapa
    redirect: engagementagency/redirectionist/redirections/update/:id
    redirectClose: engagementagency/redirectionist/redirections

update:
    title: Uppdatera
    redirect: engagementagency/redirectionist/redirections
    redirectClose: engagementagency/redirectionist/redirections
